### ISSUE TITLE
Test only 27 images

### ISSUE THREAD

**Issue by HounaidaM** [RGivisiez/Blood-Vessel-Segmentation#1]
@RGivisiez

Thank you for your code, it is beneficial to me.

I have my private dataset, and my U-net code runs correctly (train and test) on the full dataset.
I want to test the model on only 27 images. When I execute evaluate function, I meet this error :

**InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: slice index 1 of dimension 2 out of bounds.
[[{{node strided_slice_1}}]]
[[IteratorGetNext]]
[[IteratorGetNext/_4]]
(1) Invalid argument: slice index 1 of dimension 2 out of bounds.
[[{{node strided_slice_1}}]]
[[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_12429]

Function call stack:
test_function -> test_function**

Can you please help me?
thank you

**Comment by RGivisiez** [comment]
Hi @HounaidaM, can you give me more information? Which notebook are you using, Egss or Drive? Which of the algorithms are you using, U-net, M2V-net or M2U-net? 

Without having more information, I think the problem is in the format of the array that contains yours 27 images. What are the dimensions of the array where the 27 images are?

**Comment by HounaidaM** [comment]
@RGivisiez thank you for your answer
I used the Eggs code, with U-net.
My images folders contains 27 images 512X512 (originals & labels)

for those images, I used the following code : 


test_batch=2
resize_wh = 512
crop_wh = 128
#-----------------------------------------
test_image_paths = os.listdir(imgs_test)   # len(test_image_paths)=27
test_label_paths = os.listdir(label_imgs_test)    # len(test_label_paths )=27

test_image_paths = [imgs_test + i for i in test_image_paths]
test_label_paths = [label_imgs_test + i for i in test_label_paths]

test_image_paths.sort(key=lambda f: int(re.sub('\D', '', f)))
test_label_paths.sort(key=lambda f: int(re.sub('\D', '', f)))

print(len(test_image_paths))
print(len(test_label_paths))

#-----------------------------------------
#Create the source dataset from lists
test_dataset = tf.data.Dataset.from_tensor_slices((test_image_paths, test_label_paths))

#apply transformations
test_dataset = test_dataset.map(load)
test_dataset = test_dataset.map(parse_function_test)

test_dataset = test_dataset.flat_map(
    lambda image, label: tf.data.Dataset.zip((
    tf.data.Dataset.from_tensor_slices(image), 
    tf.data.Dataset.from_tensor_slices(label))
    ))

test_dataset = test_dataset.batch(test_batch).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
print(test_dataset)
#-----------------------------------
_ = model1.evaluate(test_dataset)      # error is here
#-----------------------------------
for data in test_dataset:
 
  image_cropped = data[0].numpy()
  label_cropped = data[1].numpy()

  image_pred_cropped = model1.predict(image_cropped)

  image, label, image_pred = rebuild_image(image_cropped,
                                           label_cropped,
                                           image_pred_cropped)
  
  print(label.shape)
  print(image_pred.shape)
  
  label = color_labels(label, image_pred)
  
  
  plt.figure(figsize=(20, 20))
  ax = plt.subplot(1, 2, 1)
  image = cv2.cvtColor(image.astype('float32'), cv2.IMREAD_COLOR)
 
  plt.imshow(image)
  plt.axis('off')
  
  ax = plt.subplot(1, 2, 2)
  pred_label = cv2.cvtColor(label.astype('uint8'), cv2.IMREAD_COLOR)

  plt.imshow(pred_label)

  plt.axis('off')
  plt.show()
    

Thank you very match

**Comment by RGivisiez** [comment]
@HounaidaM I was unable to reproduce the error you describe. But I think your program has some problem with the shape of the test array. The input test image shape must be of (512, 512, 3). And after pass through ```parse_function_test```,   it must be of shape (16, 128, 128, 1) (16 is the number of images generate after cropping an input image)

The code below runs without any error.

```python
# Images parameters
channels = 3
height = 512
width = 512

# Resize parameters
resize_h = 512
crop_wh = 128

test_batch = 2
```

```python
#Generate fake images and fake labels. 
#Note that both have size 3 channels.

fake_img = np.zeros((height, width, channels))
fake_img_labels = np.zeros((height, width, channels))

for idx in range(27):
  cv2.imwrite(str(idx + 1) + '.png', fake_img)
  cv2.imwrite(str(idx + 1) + 'f.png', fake_img_labels)
```
```python
#Add a print statement to see the image size.
def parse_function_test(image, label):

    image = rgb2gray(image)
    image_shape = image.shape
    label_shape = label.shape

    image = tf.py_function(clahe_equalized, [image], tf.uint8)
    image.set_shape(image_shape)

    image = tf.image.resize(image, [resize_h, width], method='nearest')
    label = tf.image.resize(label, [resize_h, width], method='nearest')

    image = tf.image.convert_image_dtype(image, tf.float32)
    label = tf.image.convert_image_dtype(label, tf.float32) / 255

    image, label = crop(image, label, crop_wh, image.shape[-1])

    print(image.shape) #Check image shape
    print(label.shape) #Check label shape

    return image, label
```

```python
test_file_names = [str(i) + '.png' for i in range(1, 27)]
test_labels = [str(i) + 'f.png' for i in range(1, 27)]

test_dataset = tf.data.Dataset.from_tensor_slices((test_file_names, test_labels))

test_dataset = test_dataset.map(load)
test_dataset = test_dataset.map(parse_function_test)

test_dataset = test_dataset.flat_map(
    lambda image, label: tf.data.Dataset.zip((
    tf.data.Dataset.from_tensor_slices(image), 
    tf.data.Dataset.from_tensor_slices(label))
    ))

test_dataset = test_dataset.batch(test_batch).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

print(test_dataset)
#Print result:
#<PrefetchDataset shapes: ((None, 128, 128, 1), (None, 128, 128, 1)), types: (tf.float32, tf.float32)>
```

**Comment by HounaidaM** [comment]
@RGivisiez 
Yes, I got the same result.
Next, if I run:
   ```
 for data in test_dataset:
       image_cropped = data[0].numpy()
       label_cropped = data[1].numpy()
    
       image_pred_cropped = model.predict(image_cropped)
        ...
```

the for loop gives me the following error:

slice index 1 of dimension 2 out of bounds.
	 [[{{node strided_slice_1}}]] [Op:IteratorGetNext]

**Comment by RGivisiez** [comment]
Using the code I sent in the previous answer, along with your images, do you get errors using the commands below?

```python
model.predict(test_dataset)
model.predict(test_dataset)
```

**Comment by HounaidaM** [comment]
The error is in the for loop, before getting to 'predict' instruction

**Comment by RGivisiez** [comment]
I still think that the problem is in the test array shape, I can't know for sure. I will be better able to provide help if you provide complete code that can reproduce the problem.

**Comment by HounaidaM** [comment]
@RGivisiez, please send me your e-mail. I will share my code on drive. 
The mine is hounaida.moalla@isetsf.rnu.tn

thank you very match

**Comment by HounaidaM** [comment]
@RGivisiez, please can you see the code and used datasets in the following link:

https://drive.google.com/drive/folders/1RqZK3A5Njwp2um6AIxkXScIIlLfBUx71?usp=sharing

NB : I work on kaggle cloud

thank you a lot

**Comment by RGivisiez** [comment]
What was causing the problems was the type of image used and the different format of the training and inference images.

**Comment by HounaidaM** [comment]
@RGivisiez thank you a lot
